const cesarAvatar = "https://pps.services.adobe.com/api/profile/E95DC580533DC6280A4C98A2@AdobeID/276";
const hugoAvatar = "/images/avatar.jpg";

const owners = {
  cesar: { name: "César Sepúlveda", role: "Director creativo", avatar: cesarAvatar },
  hugo: { name: "Hugo Macias", role: "Director de arte", avatar: hugoAvatar },
  mario: { name: "Mario González", role: "Director de arte", avatar: "" },
  suzanne: { name: "Suzanne Soria D.", role: "Copywriter", avatar: "" },
  sergio: { name: "Sergio Estrella", role: "Director de arte", avatar: "" },
  carlosAguirre: { name: "Carlos Alberto Aguirre Pesantes", role: "Postproducción", avatar: "" },
  ariana: { name: "Ariana Vera Bustamante", role: "Content manager", avatar: "" },
  steven: { name: "Steven Macías", role: "Dirección de arte", avatar: "" },
  chema: { name: "Chema Camacho", role: "Director creativo", avatar: "" },
  luis: { name: "Luis Andrés Salazar", role: "Producción", avatar: "" },
  jeshua: { name: "Jeshua Quimí", role: "Director de arte", avatar: "" },
  julio: { name: "Julio Peña", role: "Director de arte", avatar: "" },
  carlosParra: { name: "Carlos Parra", role: "Director creativo", avatar: "" },
  ricardo: { name: "Ricardo Portés", role: "Copywriter", avatar: "" },
  roberto: { name: "Roberto Zevallos", role: "Copywriter", avatar: "" },
  andres: { name: "Andrés Zuleta", role: "Director de arte", avatar: "" },
  yisus: { name: "Yisus (Jose León Fon Fay)", role: "Director creativo asociado", avatar: "" },
  ronald: { name: "Ronald Moreano", role: "Director de arte", avatar: "" },
  priscila: { name: "Priscila Chia", role: "Copywriter", avatar: "" },
};

const portfolioProjects = [
  {
    slug: "santa-hates-us-almacenes-alprecio",
    title: "Santa Hates Us - Almacenes Alprecio",
    date: "",
    category: "Campaña / Retail",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/c93040245928121.Y3JvcCwyMTYwLDE2ODksMCwyMDM.jpg",
    role: "Multiple Owners",
    source: "https://www.behance.net/gallery/245928121/Santa-Hates-Us-Almacenes-Alprecio",
    recognition: "",
    team: [owners.cesar, owners.hugo],
    highlights: [],
  },
  {
    slug: "sonidos-del-mas-alla-cementerio-general-de-guayaquil",
    title: "Sonidos del Mas Allá - Cementerio General de Guayaquil",
    date: "February 9th 2026",
    category: "Campaña / Experiencia / Cultura",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/893247243846223.Y3JvcCwxMjMyLDk2MywwLDY.jpg",
    role: "Art Directors: Hugo Macías, Mario González, Sergio Estrella",
    source: "https://www.behance.net/gallery/243846223/Sonidos-del-Mas-Alla-Cementerio-General-de-Guayaquil",
    recognition: "Mención en Lürzer’s Archive",
    team: [
      owners.cesar,
      owners.mario,
      owners.suzanne,
      owners.hugo,
      owners.sergio,
      owners.carlosAguirre,
      owners.ariana,
    ],
    highlights: [
      "Advertising Agency: La Destilería, Guayaquil.",
      "Creative Director: César Sepúlveda",
      "Copywriter: Suzanne Soria",
      "Art Directors: Hugo Macías, Mario González, Sergio Estrella",
    ],
  },
  {
    slug: "unhealthy-love-doctores-ya",
    title: "Unhealthy Love - Doctores Ya!",
    date: "May 6th 2026",
    category: "Campaña / Salud / Print",
    cover: "",
    role: "Art Directors: Hugo Macías, Sergio Estrella",
    source: "https://www.behance.net/gallery/248895969/Unhealthy-Love-Doctores-Ya",
    recognition: "",
    team: [owners.cesar, owners.sergio, owners.hugo, owners.suzanne, owners.ariana],
    highlights: [
      "Advertising Agency: La Destilería, Guayaquil.",
      "Creative Director: César Sepúlveda",
      "Copywriter: Suzanne Soria",
      "Art Directors: Hugo Macías, Sergio Estrella",
    ],
  },
  {
    slug: "brand-identity-sipsopa",
    title: "Brand Identity - SIPSOPA",
    date: "",
    category: "Branding / Identidad",
    cover: "",
    role: "Multiple Owners",
    source: "https://www.behance.net/gallery/249015395/Brand-Identity-SIPSOPA",
    recognition: "",
    team: [owners.cesar, owners.hugo],
    highlights: [],
  },
  {
    slug: "mr-domoto-canal-youtube",
    title: "MR DOMOTO | Canal Youtube",
    date: "December 11th 2025",
    category: "Branding / Contenido / Tecnología",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/544ceb240241599.Y3JvcCw1NjAsNDM4LDM5MzMsNDk.jpg",
    role: "Diseñador gráfico: Hugo Macías",
    source: "https://www.behance.net/gallery/240241599/MR-DOMOTO-Canal-Youtube",
    recognition: "",
    team: [owners.steven, owners.hugo, owners.chema, owners.luis],
    highlights: [
      "Agencia Qbit",
      "Cliente Grupo Marriott",
      "Director Creativo: José María Camacho",
      "Dirección de Arte: Steven Macías",
      "Diseñador gráfico: Hugo Macías",
      "Producción: Luis Salazar",
    ],
  },
  {
    slug: "la-mama-de-las-chaquetas-motorscorp",
    title: "La mamá de las chaquetas - Motorscorp",
    date: "May 12th 2025",
    category: "Campaña / Automotriz / Retail",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/eea512225719947.Y3JvcCwxNDE0LDExMDYsMTIwMSw1ODE.jpg",
    role: "Designer: Sergio Estrella, Jeshua Quimí",
    source: "https://www.behance.net/gallery/225719947/La-mama-de-las-chaquetas-Motorscorp",
    recognition: "",
    team: [
      owners.cesar,
      owners.carlosAguirre,
      owners.jeshua,
      owners.sergio,
      owners.suzanne,
      owners.julio,
      owners.carlosParra,
    ],
    highlights: [
      "Advertising Agency: Destilería",
      "Creative Director: César Sepúlveda, Carlos Parra",
      "Copywriter: Suzanne Soria",
      "Art Director: Julio Peña, César Sepúlveda",
      "Designer: Sergio Estrella, Jeshua Quimí",
    ],
  },
  {
    slug: "the-unstereotyped-lineup-ojo-de-iberoamerica-2025",
    title: "The Unstereotyped LineUp - Ojo de Iberoamérica 2025",
    date: "",
    category: "Campaña / Salud / Dirección de Arte",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/8e54df238580693.Y3JvcCwyMjk4LDE3OTgsOTYsMA.jpg",
    role: "Multiple Owners",
    source: "https://www.behance.net/gallery/238580693/The-Unstereotyped-LineUp-Ojo-de-Iberoamrica-2025",
    recognition: "Shortlist / mención de honor en Lápiz de Acero Iberoamérica",
    team: [owners.hugo],
    highlights: [],
  },
  {
    slug: "coca-cola-christmas-forever-young-golds-2025",
    title: "Coca-Cola - Christmas Forever | Young Golds 2025",
    date: "October 6th 2025",
    category: "Campaña / Marca / Conceptual",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/99bf33236051269.Y3JvcCwxMzgwLDEwODAsMTE5LDA.png",
    role: "Multiple Owners",
    source: "https://www.behance.net/gallery/236051269/Coca-Cola-Christmas-Forever-Young-Golds-2025",
    recognition: "",
    team: [owners.suzanne, owners.hugo],
    highlights: [],
  },
  {
    slug: "hushers-maxell-ecuador",
    title: "Hushers - Maxell Ecuador",
    date: "August 6th 2025",
    category: "Campaña / Audio / Print",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/d92ce7231995415.Y3JvcCw1NTEwLDQzMDksMTg1NCw2MTM.jpg",
    role: "Art Director: Hugo Macías, César Sepúlveda",
    source: "https://www.behance.net/gallery/231995415/Hushers-Maxell-Ecuador",
    recognition: "",
    team: [owners.cesar, owners.sergio, owners.hugo, owners.suzanne],
    highlights: [
      "Advertising Agency: Destilería",
      "Creative Director: César Sepúlveda",
      "Copywriter: Suzanne Soria",
      "Art Director: Hugo Macías, César Sepúlveda",
      "Designer: Sergio Estrella",
    ],
  },
  {
    slug: "distracted-maxell-headphones",
    title: "DISTRACTED - Maxell Headphones",
    date: "July 26th 2025",
    category: "Campaña / Print / Tecnología",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/a205ca231186873.Y3JvcCwyMjg3LDE3ODksMjgzLDM5.png",
    role: "Art Director: Hugo Macías, Jeshua Quimí, Sergio Estrella",
    source: "https://www.behance.net/gallery/231186873/DISTRACTED-Maxell-Headphones",
    recognition: "",
    team: [owners.jeshua, owners.hugo, owners.suzanne, owners.cesar, owners.sergio],
    highlights: [
      "Advertising Agency: Destilería, Guayaquil, Ecuador",
      "Creative Director: César Sepúlveda",
      "Copywriter: Suzanne Soria",
      "Art Director: Hugo Macías, Jeshua Quimí, Sergio Estrella",
    ],
  },
  {
    slug: "kiss-testing-etnia-cosmetics",
    title: "Kiss Testing - Etnia Cosmetics",
    date: "August 6th 2024",
    category: "Campaña / Belleza / Cruelty Free",
    cover: "",
    role: "Multiple Owners",
    source: "https://www.behance.net/gallery/204952501/Kiss-Testing-Etnia-Cosmetics",
    recognition: "Featured in Advertising",
    team: [owners.cesar, owners.ricardo, owners.roberto, owners.andres, owners.yisus, owners.ronald, owners.priscila],
    highlights: [
      "Advertising Agency: God Ecuador",
      "Creative Director: César Sepúlveda",
      "Associate Creative Director: José León Fon Fay \"Yisus\"",
      "Art Director: Ronald Moreano, César Sepúlveda",
      "Designer: Andrés Zuleta",
    ],
  },
];

export { portfolioProjects };
