const portfolioProjects = [
  {
    slug: "santa-hates-us-almacenes-alprecio",
    title: "Santa Hates Us - Almacenes Alprecio",
    date: "",
    category: "Campaña / Retail",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/c93040245928121.Y3JvcCwyMTYwLDE2ODksMCwyMDM.jpg",
    summary: "",
    role: "Multiple Owners",
    source: "https://www.behance.net/gallery/245928121/Santa-Hates-Us-Almacenes-Alprecio",
    recognition: "",
    team: [],
    highlights: [],
  },
  {
    slug: "sonidos-del-mas-alla-cementerio-general-de-guayaquil",
    title: "Sonidos del Mas Allá - Cementerio General de Guayaquil",
    date: "February 9th 2026",
    category: "Campaña / Experiencia / Cultura",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/893247243846223.Y3JvcCwxMjMyLDk2MywwLDY.jpg",
    summary:
      'To celebrate Halloween in a different way, we recorded the night sounds of the Guayaquil General Cemetery, turned them into symphonic scores and created an event to commemorate the "Sounds From Beyond".',
    role: "Art Directors: Hugo Macías, Mario González, Sergio Estrella",
    source: "https://www.behance.net/gallery/243846223/Sonidos-del-Mas-Alla-Cementerio-General-de-Guayaquil",
    recognition: "",
    team: [
      "César Sepúlveda",
      "Mario González",
      "Suzanne Soria D.",
      "Hugo Macias",
      "Sergio Estrella",
      "Carlos Alberto Aguirre Pesantes",
      "Ariana Vera Bustamante",
    ],
    highlights: [
      "Advertising Agency: La Destilería, Guayaquil.",
      "Creative Director: César Sepúlveda",
      "Copywriter: Suzanne Soria",
      "Art Directors: Hugo Macías, Mario González, Sergio Estrella",
    ],
  },
  {
    slug: "mr-domoto-canal-youtube",
    title: "MR DOMOTO | Canal Youtube",
    date: "December 11th 2025",
    category: "Branding / Contenido / Tecnología",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/544ceb240241599.Y3JvcCw1NjAsNDM4LDM5MzMsNDk.jpg",
    summary:
      "Creamos MR. DOMOTO, una marca pensada para acercar la domótica a las personas de forma sencilla y entretenida.",
    role: "Diseñador gráfico: Hugo Macías",
    source: "https://www.behance.net/gallery/240241599/MR-DOMOTO-Canal-Youtube",
    recognition: "",
    team: ["Steven Macías", "Hugo Macias", "Chema Camacho", "Luis Andrés Salazar"],
    highlights: [
      "Agencia Qbit",
      "Cliente Grupo Marriott",
      "Director Creativo: José María Camacho",
      "Dirección de Arte: Steven Macías",
      "Diseñador gráfico: Hugo Macías",
      "Producción: Luis Salazar",
      "Modelado 3D: Krakens",
    ],
  },
  {
    slug: "la-mama-de-las-chaquetas-motorscorp",
    title: "La mamá de las chaquetas - Motorscorp",
    date: "May 12th 2025",
    category: "Campaña / Automotriz / Retail",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/eea512225719947.Y3JvcCwxNDE0LDExMDYsMTIwMSw1ODE.jpg",
    summary: "",
    role: "Designer: Sergio Estrella, Jeshua Quimí",
    source: "https://www.behance.net/gallery/225719947/La-mama-de-las-chaquetas-Motorscorp",
    recognition: "",
    team: [
      "César Sepúlveda",
      "Carlos Alberto Aguirre Pesantes",
      "Jeshua Quimí",
      "Sergio Estrella",
      "Suzanne Soria D.",
      "Julio Peña",
      "Carlos Parra",
    ],
    highlights: [
      "Advertising Agency: Destilería",
      "Brand: Motorscorp",
      "Campaign: La mamá de las chaquetas",
      "Creative Director: César Sepúlveda, Carlos Parra",
      "Copywriter: Suzanne Soria",
      "Art Director: Julio Peña, César Sepúlveda",
      "Designer: Sergio Estrella, Jeshua Quimí",
    ],
  },
  {
    slug: "the-unstereotyped-lineup-ojo-de-iberoamerica-2025",
    title: "The Unstereotyped LineUp - Ojo de Iberoamérica 2025",
    date: "",
    category: "Campaña / Salud / Dirección de Arte",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/8e54df238580693.Y3JvcCwyMjk4LDE3OTgsOTYsMA.jpg",
    summary: "",
    role: "Multiple Owners",
    source: "https://www.behance.net/gallery/238580693/The-Unstereotyped-LineUp-Ojo-de-Iberoamrica-2025",
    recognition: "Shortlist / mención de honor en Lápiz de Acero Iberoamérica",
    team: [],
    highlights: [],
  },
  {
    slug: "coca-cola-christmas-forever-young-golds-2025",
    title: "Coca-Cola - Christmas Forever | Young Golds 2025",
    date: "October 6th 2025",
    category: "Campaña / Marca / Conceptual",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/99bf33236051269.Y3JvcCwxMzgwLDEwODAsMTE5LDA.png",
    summary:
      "The “Christmas Creep” is the global phenomenon that describes how Christmas keeps arriving earlier every year.",
    role: "Multiple Owners",
    source: "https://www.behance.net/gallery/236051269/Coca-Cola-Christmas-Forever-Young-Golds-2025",
    recognition: "",
    team: ["Suzanne Soria D.", "Hugo Macias"],
    highlights: [],
  },
  {
    slug: "hushers-maxell-ecuador",
    title: "Hushers - Maxell Ecuador",
    date: "August 6th 2025",
    category: "Campaña / Audio / Print",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/d92ce7231995415.Y3JvcCw1NTEwLDQzMDksMTg1NCw2MTM.jpg",
    summary: "",
    role: "Art Director: Hugo Macías, César Sepúlveda",
    source: "https://www.behance.net/gallery/231995415/Hushers-Maxell-Ecuador",
    recognition: "",
    team: ["César Sepúlveda", "Sergio Estrella", "Hugo Macias", "Suzanne Soria D."],
    highlights: [
      "Advertising Agency: Destilería",
      "Brand: Maxell Ecuador",
      "Campaign: Hushers",
      "Creative Director: César Sepúlveda",
      "Copywriter: Suzanne Soria",
      "Art Director: Hugo Macías, César Sepúlveda",
      "Designer: Sergio Estrella",
    ],
  },
  {
    slug: "distracted-maxell-headphones",
    title: "DISTRACTED - Maxell Headphones",
    date: "July 26th 2025",
    category: "Campaña / Print / Tecnología",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/a205ca231186873.Y3JvcCwyMjg3LDE3ODksMjgzLDM5.png",
    summary:
      "Destilería advertising agency’s out-of-home advertising and print campaign executions for Maxell Noise Cancelling Headphones.",
    role: "Art Director: Hugo Macías, Jeshua Quimí, Sergio Estrella",
    source: "https://www.behance.net/gallery/231186873/DISTRACTED-Maxell-Headphones",
    recognition: "",
    team: ["Jeshua Quimí", "Hugo Macias", "Suzanne Soria D.", "César Sepúlveda", "Sergio Estrella"],
    highlights: [
      "Advertising Agency: Destilería, Guayaquil, Ecuador",
      "Brand: Maxell Ecuador",
      'Campaign: "Distracted"',
      "Creative Director: César Sepúlveda",
      "Copywriter: Suzanne Soria",
      "Art Director: Hugo Macías, Jeshua Quimí, Sergio Estrella",
    ],
  },
  {
    slug: "modelado-cinema-4d",
    title: "Modelado | Cinema 4D",
    date: "",
    category: "Modelado 3D",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/90e4b4186261879.Y3JvcCwxMzgwLDEwODAsMTcsMA.png",
    summary: "",
    role: "Owner: Hugo Macias",
    source: "https://www.behance.net/gallery/186261879/Modelado-Cinema-4D",
    recognition: "",
    team: ["Hugo Macias"],
    highlights: [],
  },
  {
    slug: "jael-melo-social-media",
    title: "Jael Melo | Social media",
    date: "December 6th 2023",
    category: "Social Media / Marca Personal",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/439a67186188749.Y3JvcCwxMjk2LDEwMTMsMCwzMg.png",
    summary: "",
    role: "Owner: Hugo Macias",
    source: "https://www.behance.net/gallery/186188749/Jael-Melo-Social-media",
    recognition: "",
    team: ["Hugo Macias"],
    highlights: [],
  },
  {
    slug: "diseno-web-paginas-locales",
    title: "Diseño web | Páginas locales",
    date: "",
    category: "Diseño web",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/25c83b186186847.Y3JvcCwxMjk2LDEwMTMsMCwzMg.png",
    summary: "",
    role: "Owner: Hugo Macias",
    source: "https://www.behance.net/gallery/186186847/Diseno-web-Paginas-locales",
    recognition: "",
    team: ["Hugo Macias"],
    highlights: [],
  },
  {
    slug: "fcs-social-media-y-branding",
    title: "FCS | Social media y branding",
    date: "",
    category: "Social Media / Branding",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/95ab14186183143.Y3JvcCwxMzgwLDEwODAsNTEsMA.png",
    summary: "",
    role: "Owner: Hugo Macias",
    source: "https://www.behance.net/gallery/186183143/FCS-Social-media-y-branding",
    recognition: "",
    team: ["Hugo Macias"],
    highlights: [],
  },
];

export { portfolioProjects };
