const cesarAvatar = "https://pps.services.adobe.com/api/profile/E95DC580533DC6280A4C98A2@AdobeID/276";
const hugoAvatar = "/images/avatar.jpg";

const person = (name, role, avatar = "") => ({ name, role, avatar });

const credits = {
  antonio: person("Antonio Jiménez", "CEO / La Destilería"),
  monica: person("Mónica Rumbea", "CMO / La Destilería"),
  cesar: person("César Sepúlveda", "Director creativo", cesarAvatar),
  carlosParra: person("Carlos Parra", "Director creativo"),
  suzanne: person("Suzanne Soria", "Copywriter"),
  suzanneD: person("Suzanne Soria D.", "Copywriter"),
  hugo: person("Hugo Macías", "Director de arte", hugoAvatar),
  mario: person("Mario González", "Director de arte"),
  sergio: person("Sergio Estrella", "Director de arte / Designer"),
  jeshua: person("Jeshua Quimí", "Director de arte / Designer"),
  julio: person("Julio Peña", "Director de arte"),
  ariana: person("Ariana Vera", "Content manager"),
  arianaFull: person("Ariana Vera Bustamante", "Content manager / Copywriter"),
  carlosAguirre: person("Carlos Aguirre", "Postproducción"),
  carlosAguirreFull: person("Carlos Alberto Aguirre Pesantes", "Postproducción"),
  meche: person("Meche Campodónico", "Account executive / BTL executive"),
  daniel: person("Daniel Vélez", "Brand manager"),
  maika: person("Maika Urdialez", "Account executive"),
  annie: person("Annie Aguilar", "Account executive"),
  oscar: person("Oscar Borja", "Multimedia production / Director"),
  erick: person("Erick Villegas", "Sound design & composition"),
  malena: person("Malena Maldonado", "Designer"),
  andreaIcaza: person("Andrea Icaza", "Client"),
  andreaNichols: person("Andrea Nichols", "Client"),
  jisleidis: person("Jisleidis Cedeño", "Photographer"),
  eduardo: person("Eduardo Hauser", "CEO / SIPSOPA"),
  rafaella: person("Rafaella Hidalgo", "Directora de arte"),
  daniela: person("Daniela Hoyos", "Content manager"),
  annabell: person("Annabell Aguilar", "Ejecutiva de cuentas"),
  steven: person("Steven Macías", "Dirección de arte"),
  chema: person("José María Camacho", "Director creativo"),
  luis: person("Luis Salazar", "Producción"),
  krakens: person("Krakens", "Modelado 3D"),
  juanManuel: person("Juan Manuel López", "Content manager"),
  andresHidalgo: person("Andrés Hidalgo", "Client"),
};

const portfolioProjects = [
  {
    slug: "santa-hates-us-almacenes-alprecio",
    title: "Santa Hates Us - Almacenes Alprecio",
    date: "",
    category: "Campaña / Retail",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/c93040245928121.Y3JvcCwyMTYwLDE2ODksMCwyMDM.jpg",
    role: "Campaign: Santa Hates Us",
    source: "https://www.behance.net/gallery/245928121/Santa-Hates-Us-Almacenes-Alprecio",
    recognition: "",
    team: [
      credits.antonio,
      credits.monica,
      credits.cesar,
      credits.suzanne,
      person("Sergio Estrella", "Designer"),
      person("Hugo Macías", "Designer", hugoAvatar),
      credits.ariana,
      credits.meche,
      credits.daniel,
    ],
    highlights: [
      "Advertising Agency: La Destilería, Guayaquil, Ecuador",
      "Brand: Almacenes Alprecio",
      "Campaign: Santa Hates Us",
    ],
  },
  {
    slug: "mil-formas-de-decirle-tulsi",
    title: "Mil formas de decirle - Tulsi",
    date: "",
    category: "Campaña",
    cover: "",
    role: "Client: Tulsi Products",
    source: "https://www.behance.net/gallery/250914359/Mil-formas-de-decirle-Tulsi",
    recognition: "",
    team: [
      credits.antonio,
      credits.monica,
      credits.cesar,
      credits.suzanneD,
      credits.hugo,
      person("Sergio Estrella", "Art director"),
      credits.ariana,
      person("Oscar Borja", "Multimedia production"),
      credits.carlosAguirre,
      credits.maika,
      person("Tulsi Products", "Client"),
    ],
    highlights: [
      "Advertising Agency: La Destilería, Guayaquil",
      "Client: Tulsi Products",
    ],
  },
  {
    slug: "unseen-rage-liaisons",
    title: "UNSEEN RAGE - LIAISONS",
    date: "",
    category: "Dirección de arte",
    cover: "",
    role: "Art Director: Hugo Macías",
    source: "https://www.behance.net/gallery/249167545/UNSEEN-RAGE-LIAISONS",
    recognition: "",
    team: [credits.suzanne, credits.hugo],
    highlights: ["Copywriter: Suzanne Soria", "Art Director: Hugo Macías"],
  },
  {
    slug: "sonidos-del-mas-alla-cementerio-general-de-guayaquil",
    title: "Sonidos del Mas Allá - Cementerio General de Guayaquil",
    date: "February 9th 2026",
    category: "Campaña / Experiencia / Cultura",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/893247243846223.Y3JvcCwxMjMyLDk2MywwLDY.jpg",
    role: "Art Directors: Hugo Macías, Mario González, Sergio Estrella",
    source: "https://www.behance.net/gallery/243846223/Sonidos-del-Mas-Alla-Cementerio-General-de-Guayaquil",
    recognition: "Mención en Lürzer’s Archive",
    team: [
      credits.antonio,
      credits.monica,
      credits.cesar,
      credits.suzanne,
      credits.hugo,
      credits.mario,
      credits.sergio,
      credits.malena,
      credits.ariana,
      credits.carlosAguirre,
      credits.erick,
      credits.annie,
      credits.maika,
      credits.meche,
      credits.andreaIcaza,
    ],
    highlights: [
      "Advertising Agency: La Destilería, Guayaquil",
      "Sound Design & Composition: Erick Villegas",
      "Client: Andrea Icaza",
    ],
  },
  {
    slug: "unhealthy-love-doctores-ya",
    title: "Unhealthy Love - Doctores Ya!",
    date: "May 6th 2026",
    category: "Campaña / Salud / Print",
    cover: "",
    role: "Art Directors: Hugo Macías, Sergio Estrella",
    source: "https://www.behance.net/gallery/248895969/Unhealthy-Love-Doctores-Ya",
    recognition: "",
    team: [
      credits.antonio,
      credits.monica,
      credits.cesar,
      credits.suzanne,
      credits.hugo,
      credits.sergio,
      credits.ariana,
      credits.jisleidis,
      credits.oscar,
      credits.maika,
      credits.andreaNichols,
    ],
    highlights: [
      "Advertising Agency: La Destilería, Guayaquil",
      "Set Advisor: Oscar Borja",
      "Client: Andrea Nichols",
    ],
  },
  {
    slug: "brand-identity-sipsopa",
    title: "Brand Identity - SIPSOPA",
    date: "",
    category: "Branding / Identidad",
    cover: "",
    role: "Cliente: SIPSOPA",
    source: "https://www.behance.net/gallery/249015395/Brand-Identity-SIPSOPA",
    recognition: "",
    team: [
      credits.eduardo,
      credits.antonio,
      credits.monica,
      credits.cesar,
      credits.carlosParra,
      person("Suzanne Soria", "Redactora creativa"),
      credits.rafaella,
      person("Sergio Estrella", "Diseñador multimedia"),
      person("Hugo Macías", "Diseñador multimedia", hugoAvatar),
      person("Jeshua Quimí", "Diseñador multimedia"),
      credits.daniela,
      credits.arianaFull,
      credits.annabell,
      credits.carlosAguirre,
    ],
    highlights: [
      "Cliente: SIPSOPA",
      "Agencia: Destilería",
      "Post Producción: Carlos Aguirre",
    ],
  },
  {
    slug: "mr-domoto-canal-youtube",
    title: "MR DOMOTO | Canal Youtube",
    date: "December 11th 2025",
    category: "Branding / Contenido / Tecnología",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/544ceb240241599.Y3JvcCw1NjAsNDM4LDM5MzMsNDk.jpg",
    role: "Proyecto: Mr DOMOTO",
    source: "https://www.behance.net/gallery/240241599/MR-DOMOTO-Canal-Youtube",
    recognition: "",
    team: [
      credits.chema,
      credits.steven,
      person("Hugo Macías", "Diseñador gráfico", hugoAvatar),
      credits.luis,
      credits.krakens,
    ],
    highlights: [
      "Agencia: Qbit",
      "Cliente: Grupo Marriott",
      "Proyecto: Mr DOMOTO",
    ],
  },
  {
    slug: "la-mama-de-las-chaquetas-motorscorp",
    title: "La mamá de las chaquetas - Motorscorp",
    date: "May 12th 2025",
    category: "Campaña / Automotriz / Retail",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/eea512225719947.Y3JvcCwxNDE0LDExMDYsMTIwMSw1ODE.jpg",
    role: "Campaign: La mamá de las chaquetas",
    source: "https://www.behance.net/gallery/225719947/La-mama-de-las-chaquetas-Motorscorp",
    recognition: "",
    team: [
      credits.antonio,
      credits.monica,
      credits.cesar,
      credits.carlosParra,
      credits.suzanne,
      credits.julio,
      person("César Sepúlveda", "Art director", cesarAvatar),
      person("Hugo Macías", "Art director", hugoAvatar),
      person("Sergio Estrella", "Designer"),
      person("Jeshua Quimí", "Designer"),
      credits.juanManuel,
      credits.ariana,
      credits.meche,
      person("Oscar Borja", "Director"),
      credits.carlosAguirre,
    ],
    highlights: [
      "Advertising Agency: Destilería",
      "Brand: Motorscorp",
      "Campaign: La mamá de las chaquetas",
    ],
  },
  {
    slug: "the-unstereotyped-lineup-ojo-de-iberoamerica-2025",
    title: "The Unstereotyped LineUp - Ojo de Iberoamérica 2025",
    date: "",
    category: "Campaña / Salud / Dirección de Arte",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/8e54df238580693.Y3JvcCwyMjk4LDE3OTgsOTYsMA.jpg",
    role: "Jóvenes Profesionales 2025",
    source: "https://www.behance.net/gallery/238580693/The-Unstereotyped-LineUp-Ojo-de-Iberoamrica-2025",
    recognition: "Shortlist Jóvenes Profesionales 2025",
    team: [
      credits.suzanne,
      person("Ariana Vera", "Copywriter"),
      credits.mario,
      credits.hugo,
    ],
    highlights: ["Reconocimiento: Shortlist Jóvenes Profesionales 2025"],
  },
  {
    slug: "coca-cola-christmas-forever-young-golds-2025",
    title: "Coca-Cola - Christmas Forever | Young Golds 2025",
    date: "October 6th 2025",
    category: "Campaña / Marca / Conceptual",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/99bf33236051269.Y3JvcCwxMzgwLDEwODAsMTE5LDA.png",
    role: "Young Golds 2025",
    source: "https://www.behance.net/gallery/236051269/Coca-Cola-Christmas-Forever-Young-Golds-2025",
    recognition: "",
    team: [credits.suzanne, credits.hugo],
    highlights: [],
  },
  {
    slug: "hushers-maxell-ecuador",
    title: "Hushers - Maxell Ecuador",
    date: "August 6th 2025",
    category: "Campaña / Audio / Print",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/d92ce7231995415.Y3JvcCw1NTEwLDQzMDksMTg1NCw2MTM.jpg",
    role: "Campaign: Hushers",
    source: "https://www.behance.net/gallery/231995415/Hushers-Maxell-Ecuador",
    recognition: "",
    team: [
      credits.antonio,
      credits.monica,
      credits.cesar,
      credits.suzanne,
      credits.hugo,
      person("César Sepúlveda", "Art director", cesarAvatar),
      person("Sergio Estrella", "Designer"),
      credits.ariana,
      credits.meche,
      credits.andresHidalgo,
    ],
    highlights: [
      "Advertising Agency: Destilería",
      "Brand: Maxell Ecuador",
      "Campaign: Hushers",
    ],
  },
  {
    slug: "distracted-maxell-headphones",
    title: "DISTRACTED - Maxell Headphones",
    date: "July 26th 2025",
    category: "Campaña / Print / Tecnología",
    cover: "https://mir-s3-cdn-cf.behance.net/projects/404/a205ca231186873.Y3JvcCwyMjg3LDE3ODksMjgzLDM5.png",
    role: "Campaign: Distracted",
    source: "https://www.behance.net/gallery/231186873/DISTRACTED-Maxell-Headphones",
    recognition: "",
    team: [
      credits.antonio,
      credits.monica,
      credits.cesar,
      credits.suzanne,
      credits.hugo,
      credits.jeshua,
      credits.sergio,
      credits.ariana,
      credits.meche,
      credits.andresHidalgo,
    ],
    highlights: [
      "Advertising Agency: Destilería, Guayaquil, Ecuador",
      "Brand: Maxell Ecuador",
      "Campaign: Distracted",
    ],
  },
];

export { portfolioProjects };
