const recoverySections = ["Referencia", "Estructura", "Pendientes", "Notas"];

const priorityProjects = [
  {
    slug: "importadora-ivma",
    title: "Importadora IVMA",
    domain: "importadoraivma.com.ec",
    status: "Activo",
    recoverability: "Muy alta",
    sector: "Importadora / eCommerce",
    variant: "commerce",
    accent: "#E7D66B",
    url: "https://importadoraivma.com.ec/",
    nav: ["Inicio", "Tienda", "Nosotros", "Login"],
    heroTitle: "Tecnologia avanzada para potenciar tu trabajo agricola",
    cta: "Explorar tienda",
    finding: "Home, tienda, nosotros, productos, textos e imagenes accesibles.",
    nextAction: "Clonar contenido y assets antes de que cambie.",
    sections: ["Tienda", "Productos", "Nosotros", "Contacto"],
    highlight: "Catalogo comercial con enfoque funcional y conversion directa.",
    description: "Importadora de maquinaria agricola y repuestos, con tienda online, mensajes comerciales directos y enfoque en distribuidores.",
  },
  {
    slug: "impetu-gym",
    title: "Impetu Gym",
    domain: "impetugymecu.com",
    status: "Activo",
    recoverability: "Muy alta",
    sector: "Fitness / Clases",
    variant: "fitness",
    accent: "#F2D34A",
    url: "https://impetugymecu.com/",
    nav: ["Inicio", "Planes", "Clases", "Horarios"],
    heroTitle: "Entrena con impetu",
    cta: "Ver planes",
    finding: "Sitio extenso con clases, planes, equipo, horarios e imagenes accesibles.",
    nextAction: "Crear copia estatica completa y capturas desktop/mobile.",
    sections: ["Planes", "Clases", "Equipo", "Horarios"],
    highlight: "Experiencia energetica orientada a membresias y comunidad fitness.",
    description: "Landing fitness pensada para vender membresias, presentar clases y construir una sensacion de comunidad activa.",
  },
  {
    slug: "sanfarma-ecu",
    title: "Sanfarma Ecuador",
    domain: "sanfarmaecu.com",
    status: "Activo",
    recoverability: "Alta",
    sector: "Salud / Farmacia",
    variant: "health",
    accent: "#7BD8C6",
    url: "https://sanfarmaecu.com/",
    nav: ["Inicio", "Productos", "Sucursales", "Contacto"],
    heroTitle: "Cuidamos de tu salud",
    cta: "Conocer servicios",
    finding: "La portada responde y conserva contenido.",
    nextAction: "Mapear rutas internas y descargar assets.",
    sections: ["Servicios", "Productos", "Cobertura", "Contacto"],
    highlight: "Presentacion clara para confianza, cercania y acceso rapido a informacion.",
    description: "Sitio de salud y farmacia con arquitectura simple para comunicar confianza, cobertura y acceso rapido a informacion.",
  },
  {
    slug: "fcs-ecuador",
    title: "FCS Ecuador",
    domain: "fcs.ec",
    status: "Activo",
    recoverability: "Muy alta",
    sector: "Food Consultancy Service",
    variant: "consulting",
    accent: "#8DDC78",
    url: "https://fcs.ec/",
    nav: ["Inicio", "Nosotros", "Servicios", "Registro"],
    heroTitle: "Soluciones, productos y servicios a la industria de alimentos",
    cta: "Descubre mas",
    finding: "Sitio de Food Consultancy Service accesible.",
    nextAction: "Clonar paginas, textos, imagenes y estructura.",
    sections: ["Consultoria", "Procesos", "Marcas", "Contacto"],
    highlight: "Arquitectura orientada a servicios, respaldo tecnico y soluciones para alimentos.",
    description: "Sitio corporativo para consultoria alimentaria, sistemas de gestion, capacitacion, asuntos regulatorios e innovacion.",
  },
  {
    slug: "kerd",
    title: "Kerd",
    domain: "kerd.com.ec",
    status: "Activo",
    recoverability: "Muy alta",
    sector: "Soluciones integrales",
    variant: "industrial",
    accent: "#7CB7FF",
    url: "https://kerd.com.ec/",
    nav: ["Inicio", "Servicios", "Contacto"],
    heroTitle: "Lideres en pisos industriales",
    cta: "Conocer servicios",
    finding: "Sitio de soluciones integrales accesible.",
    nextAction: "Clonar inmediatamente.",
    sections: ["Soluciones", "Procesos", "Sectores", "Contacto"],
    highlight: "Sistema visual corporativo para explicar servicios de forma ordenada.",
    description: "Web de soluciones industriales para pisos epoxicos, pintura e impermeabilizacion, con enfoque tecnico y comercial.",
  },
  {
    slug: "ivolution",
    title: "Ivolution",
    domain: "ivolution.ec",
    status: "Activo",
    recoverability: "Muy alta",
    sector: "Tecnologia / Innovacion",
    variant: "sporttech",
    accent: "#A6C8FF",
    url: "https://ivolution.ec/",
    nav: ["Inicio", "Tienda", "Nosotros", "Contacto"],
    heroTitle: "Potencia tu rendimiento con Ivolution",
    cta: "Explorar equipos",
    finding: "Home y contenido principal accesibles.",
    nextAction: "Clonar inmediatamente.",
    sections: ["Innovacion", "Servicios", "Casos", "Contacto"],
    highlight: "Lenguaje digital sobrio para comunicar tecnologia y crecimiento.",
    description: "Ecommerce y landing de equipos inerciales, software deportivo, modelado 3D y productos de entrenamiento.",
  },
  {
    slug: "experiencia-fit360",
    title: "Experiencia Fit360",
    domain: "experienciafit360.com",
    status: "Activo",
    recoverability: "Alta",
    sector: "Eventos / Fitness",
    variant: "event",
    accent: "#FF7A59",
    url: "https://experienciafit360.com/",
    nav: ["Inicio", "Evento", "Agenda", "Registro"],
    heroTitle: "Experiencia Fit360",
    cta: "Registrarse",
    finding: "Pagina de eventos accesible.",
    nextAction: "Mapear eventos, imagenes y paginas internas.",
    sections: ["Evento", "Agenda", "Entrenadores", "Registro"],
    highlight: "Landing de evento con ritmo visual, llamados de accion y estructura informativa.",
    description: "Landing de experiencia fitness creada para comunicar evento, energia y conversion a registro.",
  },
  {
    slug: "destileria",
    title: "Destileria",
    domain: "destileria.ec",
    status: "Activo",
    recoverability: "Muy alta",
    sector: "Agencia creativa",
    variant: "creative",
    accent: "#FF6B6B",
    url: "https://destileria.ec/",
    nav: ["Trabajos", "Nosotros", "Academia", "Contacto"],
    heroTitle: "Nos tomamos el disfrute creativo muy en serio",
    cta: "Brindemos juntos",
    finding: "Sitio de agencia creativa accesible y con bastante contenido.",
    nextAction: "Clonar estructura, portafolio, textos y assets.",
    sections: ["Agencia", "Casos", "Servicios", "Contacto"],
    highlight: "Portafolio de agencia con enfoque editorial y presentacion de casos.",
    description: "Sitio editorial de agencia creativa con narrativa de marca, casos, clientes, academia y tono cultural propio.",
  },
  {
    slug: "dr-omar-chungata",
    title: "Dr. Omar Chungata",
    domain: "dromarchungata.ec",
    status: "Activo",
    recoverability: "Muy alta",
    sector: "Medicina",
    variant: "medical",
    accent: "#9BE7D8",
    url: "https://dromarchungata.ec/",
    nav: ["Inicio", "Biografia", "Servicios", "Contacto"],
    heroTitle: "Dr. Omar Chungata Pelaez",
    cta: "Agendar cita",
    finding: "Sitio medico accesible.",
    nextAction: "Clonar paginas, especialidades, imagenes y datos.",
    sections: ["Especialidades", "Trayectoria", "Pacientes", "Contacto"],
    highlight: "Presencia medica centrada en confianza, claridad y conversion a consulta.",
    description: "Web medica orientada a trayectoria, servicios quirurgicos, confianza profesional y contacto para citas.",
  },
  {
    slug: "cepec",
    title: "CEPEC",
    domain: "cepec.com.ec",
    status: "Activo",
    recoverability: "Muy alta",
    sector: "Logistica / Soluciones",
    variant: "logistics",
    accent: "#F3B35A",
    url: "https://cepec.com.ec/",
    nav: ["Inicio", "Historia", "Servicios", "Infraestructura"],
    heroTitle: "Almacenamiento confiable. Logistica resuelta.",
    cta: "Conocer soluciones",
    finding: "Sitio de soluciones logisticas accesible.",
    nextAction: "Clonar paginas y assets.",
    sections: ["Soluciones", "Operaciones", "Cobertura", "Contacto"],
    highlight: "Sitio corporativo para ordenar servicios logisticos y propuesta comercial.",
    description: "Web corporativa de almacenamiento logistico con enfasis en inventarios, continuidad operativa e infraestructura.",
  },
];

const archiveProjects = [
  ["oscar-naranjo-cirujano", "Oscar Naranjo Cirujano", "oscarnaranjocirujano.com.ec", "Suspendido", "Alta", "Medicina estetica", "#D9C8B8", "La cuenta de hosting muestra una pagina de suspension.", "Buscar Wayback y solicitar respaldo al proveedor de hosting."],
  ["cirugias-vital", "Cirugias Vital", "cirugiasvital.com", "Instalacion / placeholder", "Media", "Salud", "#A7D8FF", "Responde como una instalacion WordPress generica o incompleta.", "Priorizar versiones historicas; revisar wp-content y hosting."],
  ["grs-ecu", "GRS Ecuador", "grs-ecu.com", "No verificable", "Media", "Grupo empresarial", "#CBD5E1", "El dominio no pudo recuperarse correctamente durante la auditoria.", "Consultar Wayback, DNS y proveedor anterior."],
  ["sofer-medical", "Sofer Medical", "sofermedical.com.ec", "No verificable", "Media", "Salud", "#B7E4D8", "No se obtuvo una pagina utilizable durante la auditoria.", "Wayback, busquedas por marca y redes sociales."],
  ["puente-marisco", "Puente Marisco", "puentemarisco.com", "No verificable", "Media", "Gastronomia", "#6EC6D9", "No se obtuvo una pagina utilizable durante la auditoria.", "Wayback, Google Images y perfiles sociales."],
  ["orion-studio", "Orion Studio", "orionstudio.ec", "No verificable", "Media", "Estudio creativo", "#B69CFF", "No se obtuvo una pagina utilizable durante la auditoria.", "Wayback, Behance/Instagram y archivos locales."],
  ["importadora-jorua", "Importadora Jorua", "importadorajorua.com", "No verificable", "Media", "Importadora", "#E1C16E", "No se obtuvo una pagina utilizable durante la auditoria.", "Wayback y busqueda de catalogo/productos."],
  ["dr-johnny-ramirez", "Dr. Johnny Ramirez", "drjohnnyramirez.com", "No verificable", "Media", "Medicina", "#C2E7FF", "No se obtuvo una pagina utilizable durante la auditoria.", "Wayback, perfiles medicos y capturas disponibles."],
  ["regalart", "Regalart", "regalart.com.ec", "No verificable", "Media", "Regalos / Retail", "#F1A6B8", "No se obtuvo una pagina utilizable durante la auditoria.", "Wayback, redes y catalogos visuales."],
  ["quinta-alaia", "Quinta Alaia", "quintaalaia.com", "No verificable", "Media", "Venue / Eventos", "#B6D7A8", "No se obtuvo una pagina utilizable durante la auditoria.", "Wayback, Booking/redes/mapas y fotografias."],
  ["jael-melo-olvera", "Jael Melo Olvera", "jaelmeloolvera.com", "No verificable", "Media", "Marca personal", "#F3C0D7", "No se obtuvo una pagina utilizable durante la auditoria.", "Wayback y busqueda por nombre/marca."],
  ["etika", "Etika", "etika.com.ec", "No verificable", "Media", "Marca / Retail", "#E7E1C5", "No se obtuvo una pagina utilizable durante la auditoria.", "Wayback, redes y registros de marca."],
  ["kub", "KUB", "kub.com.ec", "No verificable", "Media", "Marca / Servicios", "#9BB7D4", "No se obtuvo una pagina utilizable durante la auditoria.", "Wayback y busqueda de paginas indexadas."],
  ["vision-colectiva", "Vision Colectiva", "visioncolectiva.ec", "No verificable", "Media", "Comunidad / Comunicacion", "#91D8B5", "No se obtuvo una pagina utilizable durante la auditoria.", "Wayback, redes y piezas del portafolio."],
  ["jose-muzo", "Jose Muzo", "jmuzo.com", "No verificable", "Media", "Marca personal / Profesional", "#D2B48C", "No se obtuvo una pagina utilizable durante la auditoria.", "Wayback y busqueda por nombre profesional."],
];

const historicalProjects = archiveProjects.map(
  ([slug, title, domain, status, recoverability, sector, accent, finding, nextAction]) => ({
    slug,
    title,
    domain,
    status,
    recoverability,
    sector,
    accent,
    finding,
    nextAction,
    priority: "Recuperacion historica",
    level: "Nivel D",
    variant: "archive",
    url: null,
    nav: recoverySections,
    heroTitle: title,
    cta: "Reconstruir archivo",
    description: finding,
    sections: recoverySections,
    highlight: "Proyecto archivado para segunda capa de investigacion y reconstruccion editorial.",
  }),
);

const webDesignProjects = [
  ...priorityProjects.map((project) => ({
    ...project,
    priority: "Prioridad 1",
    level: "Nivel B",
    description: project.description ?? project.highlight,
  })),
  ...historicalProjects,
];

export { webDesignProjects };
